// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4P4gnSQVIFhUIg464LMH_T68LhpsffbY',
    appId: '1:596014931235:web:fa55d081ab6416db324096',
    messagingSenderId: '596014931235',
    projectId: 'fitness-tracker-des',
    authDomain: 'fitness-tracker-des.firebaseapp.com',
    storageBucket: 'fitness-tracker-des.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbV1rJq0o5gA7KMBX66-LpTebUWQWcSNI',
    appId: '1:596014931235:android:b50bf50d00f38b65324096',
    messagingSenderId: '596014931235',
    projectId: 'fitness-tracker-des',
    storageBucket: 'fitness-tracker-des.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKlyBXDX2siMYdiZjhnWEpbp61eUhnkrU',
    appId: '1:596014931235:ios:e5b7d6cad8ca4545324096',
    messagingSenderId: '596014931235',
    projectId: 'fitness-tracker-des',
    storageBucket: 'fitness-tracker-des.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKlyBXDX2siMYdiZjhnWEpbp61eUhnkrU',
    appId: '1:596014931235:ios:e5b7d6cad8ca4545324096',
    messagingSenderId: '596014931235',
    projectId: 'fitness-tracker-des',
    storageBucket: 'fitness-tracker-des.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4P4gnSQVIFhUIg464LMH_T68LhpsffbY',
    appId: '1:596014931235:web:12ccef6ebda439b5324096',
    messagingSenderId: '596014931235',
    projectId: 'fitness-tracker-des',
    authDomain: 'fitness-tracker-des.firebaseapp.com',
    storageBucket: 'fitness-tracker-des.firebasestorage.app',
  );

}